//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanti_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvantiTestEntities : DbContext
    {
        public AvantiTestEntities()
            : base("name=AvantiTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<motoqueros> motoqueros { get; set; }
        public virtual DbSet<pedidoitems> pedidoitems { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<productos> productos { get; set; }
    }
}
