//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanti_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedidos()
        {
            this.pedidoitems = new HashSet<pedidoitems>();
        }
    
        public int ID_pedido { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int PedidoN { get; set; }
        public int ID_Cliente { get; set; }
        public string Notas { get; set; }
        public double Total { get; set; }
        public double Efectivo { get; set; }
        public double Vuelto { get; set; }
        public bool abonajusto { get; set; }
        public int ID_Motoquero { get; set; }
        public string Estado { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual motoqueros motoqueros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedidoitems> pedidoitems { get; set; }
    }
}
