//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avanti_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidoitems
    {
        public int ID_pedidoitem { get; set; }
        public int ID_pedido { get; set; }
        public int ID_producto { get; set; }
        public string Producto { get; set; }
        public double Cantidad { get; set; }
        public double Precio { get; set; }
    
        public virtual pedidos pedidos { get; set; }
    }
}
